### ISSUE TITLE
How to build gencode.comprehensive.splice.junctions.txt?

### ISSUE THREAD

**Issue by naumenko-sa** [berylc/MendelianRNA-seq#1]
Hello Beryl!
Thanks for the excellent tool!

In the Analysis/NormalizeSpliceJunctionValues.py a junction database is needed:
gencode.comprehensive.splice.junctions.txt

How to build it?

Sergey

**Comment by berylc** [comment]
Hi Sergey, 
My apologies for the delayed response. I am in the process of writing a blog post and revamping the GitHub directory so you can get a sense of how to run the code . I expect that to be ready in about a week!

For now please find the specific file you were looking for here: 
https://personal.broadinstitute.org/berylc/MendelianRNAseq/gencode.comprehensive.splice.junctions.txt

Hope that helps! 
All the best,
Beryl

**Comment by naumenko-sa** [comment]
Thanks a lot, Beryl!
