### ISSUE TITLE
A practical readme file is required

### ISSUE THREAD

**Issue by CancerGenome** [berylc/MendelianRNA-seq#3]
Hi Bery,

I am working on cardiovascular disease and plan to use RNA-seq to test for causing variant detection. Your paper looks promising and well suited to our study. My question is: if I want to use you pipelines for analysis, are there any readme or tutorial files to follow?

Thanks,

**Comment by ekofman** [comment]
Hello @berylc ,

I was wondering how the NMD_genes.list file was generated. I am trying to replicate it via the Ensembl biomart downloader, and cannot achieve the same coordinates as are listed for the NEB example given in the examples folder, which I'd like to use as a sanity benchmark.

Thanks for the advice,

Eric

**Comment by berylc** [comment]
Hey @CancerGenome so sorry I seem to have completely missed your message. 

Yes we have a walk through available here : 
https://macarthurlab.org/2017/05/31/improving-genetic-diagnosis-in-mendelian-disease-with-transcriptome-sequencing-a-walk-through/

Gives exact commands to use for specific purposes, also has some considerations about study design.

**Comment by berylc** [comment]
@ekofman these are hg19 coordinates I generated from parsing the RNASEQC refGene output. Perhaps it has to do with how UTRs are treated? 

https://www.dropbox.com/s/zuelztb4k4ftv03/refGene.txt?dl=0
